// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adodixltwxgxlecqocgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkb2RpeGx0d3hneGxlY3FvY2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MzU5MDEsImV4cCI6MjA2NTExMTkwMX0.uwC1ItC69FHvOXCTSwSbVXMmTxEpy-0zu_SfvDvnykY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);